
language: php
php:
  - '7.1'

conditions: v1

sudo: required

addons:
  chrome: stable


stages:
  - name: comment pr
    if: type = pull_request AND branch = master

jobs:
  include:
    - stage: comment pr
      before_install:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ] ; then php -f commentGithubPullrequest.php; fi
      script: 
        - echo comment pr
      after_script:
        - env
        - echo $TRAVIS_TEST_RESULT
